### ISSUE TITLE
Unable to find image 'crawler:latest' 

### ISSUE THREAD

**Issue by DeonWinchester** [sodaling/FastestBilibiliDownloader#6]
MacOS : 10.15.3
Docker version 19.03.5, build 633a0ea

➜  FastestBilibiliDownloader git:(master) make run
docker run -it  -v /Users/deon/FastestBilibiliDownloader/download:/download crawler
Unable to find image 'crawler:latest' locally
docker: Error response from daemon: pull access denied for crawler, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make: *** [run] Error 125
➜  FastestBilibiliDownloader git:(master) docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED              SIZE
downloader                   latest              0c02c2471788        35 seconds ago       63.9MB
<none>                       <none>              5ee2db5b115b        About a minute ago   459MB

**Comment by sodaling** [comment]
这个之前已经发现了，在最新的commit更新了makefile，你可以拉一下最新的代码看看能运行不。
对应的commit是
9391a42c2ca53e4c8ecdd8a81991ad51d84fbfef
