### ISSUE TITLE
重命名地狱

### ISSUE THREAD

**Issue by DeonWinchester** [sodaling/FastestBilibiliDownloader#7]
下载分P视频可以自动命名原P的标题嘛？

**Comment by sodaling** [comment]
我明白你什么意思了，我周末看看怎么弄。这是个好建议呢

**Comment by sodaling** [comment]
这边说声抱歉,因为是api的原因,直接输入aid下载的时候,下载对应视频的api是没包括视频名称信息的,这边如果要找视频名词信息的话就得费一番折腾,我后期看看怎么解决最优雅
