### ISSUE TITLE
在Win系统下，文件夹名称中有特殊字符

### ISSUE THREAD

**Issue by justin201802** [sodaling/FastestBilibiliDownloader#8]
`
A:\FastestBilibiliDownloader-master\cmd>go run start-concurrent-engine.go
Can't locate your ffmeg.The video your download can't be merged
Please enter your id type(`aid` or `upid`)
aid
Please enter your id
92756064
2020/03/14 20:52:47 Start working.
2020/03/14 20:52:47 Item Saver:got item #0: &{0xc000070300}
panic: mkdir A:\FastestBilibiliDownloader-master\cmd/download/92756064:92756064: The directory name is invalid.

goroutine 22 [running]:
simple-golang-crawler/tool.GetAidFileDownloadDir(0x5875860, 0xc000011c78, 0x8, 0x0, 0x0)
        A:/FastestBilibiliDownloader-master/tool/path.go:18 +0x218
simple-golang-crawler/fetcher.GenVideoFetcher.func1(0xc00022c036, 0xe9, 0x0, 0x0, 0x0, 0x0, 0x0)
        A:/FastestBilibiliDownloader-master/fetcher/downloader.go:52 +0x9a9
simple-golang-crawler/engine.work(0xc0002041a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        A:/FastestBilibiliDownloader-master/engine/concurrent.go:105 +0x5e
simple-golang-crawler/engine.CreateWorker.func1(0xd94008, 0xc000064d10, 0xc000090240, 0xc000090000)
        A:/FastestBilibiliDownloader-master/engine/concurrent.go:93 +0xaa
created by simple-golang-crawler/engine.CreateWorker
        A:/FastestBilibiliDownloader-master/engine/concurrent.go:89 +0x64
exit status 2
`

不知道是不是要创建“92756064:92756064”这个目录， 冒号（：）在Win下是不允许作为文件名的。
我已经手动创建了”A:\FastestBilibiliDownloader-master\cmd\download\92756064“这个目录， 还是不能运行程序。

**Comment by sodaling** [comment]
收到了,大概知道什么原因了,我这边周末修复一下,非常感谢你的热心呢

**Comment by sodaling** [comment]
已经把路径的冒号改为下划线了,应该不会在Windows出现这个问题了
